# numpy
* Numerical python의 약자로 대표적인 파이썬 기반 수치해석 라이브러리다.
* 파이썬 리스트보다 적은 메모리 사용량과 빠른 성능을 지니고 있다.
* 선형대수, 통계관련 여러 함수를 내장하고 있다.

## ndarray
* numpy에서 사용되는 다차운 리스트를 표현할때 사용되는 데이터 타입을 의미한다.

In [1]:
import numpy as np

## np.array

In [2]:
x = np.array([1,2,3,4,5])

type(x)

numpy.ndarray

## np.arange

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## np.ones

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## np.zeros

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## np.empty

In [9]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.full

In [10]:
np.full((2, 3, 4), 5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

## np.eye

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.linspace

In [13]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [15]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## reshape
* ndarray의 형태또는 차원을 바꾸기 위해 사용한다.

In [19]:
x = np.arange(1,51)
print(x)

x.reshape(2, 25)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])