In [1]:
import numpy as np

## ravel, np.ravel
* 다차원배열을 1차원으로 변경할 수 있다.
* 'order' 파라미터
    * 'C' - row 우선 변경
    * 'F - column 우선 변경

In [11]:
x = np.arange(15).reshape(3, 5)
print(x)

print('열 우선 변경 :',np.ravel(x, order='F'))
print('행 우선 변경 :',np.ravel(x, order='C'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
열 우선 변경 : [ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]
행 우선 변경 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
y = x.ravel()

y[0] = 200
print(x)
print(y)

[[200   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[200   1   2   3   4   5   6   7   8   9  10  11  12  13  14]


## flatten
* 다차원 배열을 1차원으로 변경가능하다.
* ravel과는 달리 원본 데이터가 아닌 복사본을 생성하여 변경한다.
* 'order' 파라미터
    * 'C' - row 우선 변경
    * 'F - column 우선 변경

In [14]:
x = np.arange(15).reshape(3, 5)
print(x)

x1 = x.flatten(order='F')
x2 = x.flatten(order='C')

print('열 우선 변경 :',x1)
print('행 우선 변경 :',x2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
열 우선 변경 : [ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]
행 우선 변경 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
x1[0] = 200
print(x1)
print(x)

[200   5  10   1   6  11   2   7  12   3   8  13   4   9  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## reshape
* array의 shape을 다른 차원으로 변경할 수 있다.
* reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능하다.
* 몇가지의 차원을 적은 후 -1을 채우면 알아서 전체 원소의 개수를 맞춰준다.

In [16]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [18]:
x = np.arange(36).reshape(3,-1)
print(x)
print(x.shape)
print(x.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
(3, 12)
2


In [19]:
x = np.arange(36).reshape(3,3,-1)
print(x)
print(x.shape)
print(x.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
