In [1]:
import numpy as np

## [numpy documentation](https://www.numpy.org/devdocs/reference/)
* numpy에서 제공되는 함수등에 대한 문서이다.

## 연산 함수
* add 
* subtract
* multiply
* divide

## 연산자
* +
* -
* *
* /

In [3]:
x = np.arange(20).reshape(4, 5)
y = np.random.rand(20).reshape(4, 5)

np.add(x,y)
np.subtract(x,y)

array([[-0.16214667,  0.13146362,  1.33800869,  2.74451135,  3.46192415],
       [ 4.86085173,  5.51316031,  6.15966398,  7.39157929,  8.0400107 ],
       [ 9.170276  , 10.96799978, 11.37232924, 12.35382413, 13.82087279],
       [14.82362799, 15.74938862, 16.84166811, 17.57423499, 18.31835159]])

In [4]:
x + y
x - y

array([[-0.16214667,  0.13146362,  1.33800869,  2.74451135,  3.46192415],
       [ 4.86085173,  5.51316031,  6.15966398,  7.39157929,  8.0400107 ],
       [ 9.170276  , 10.96799978, 11.37232924, 12.35382413, 13.82087279],
       [14.82362799, 15.74938862, 16.84166811, 17.57423499, 18.31835159]])

## 통계 함수
* 평균 mean
* 분산 var
* 표준편차 std
* 중앙 median
* 최댓값 max
* 최솟값 min
* 최댓값의 인덱스 argmax
* 최솟값의 인덱스 argmin

In [6]:
x = np.arange(20).reshape(4, 5)

print(np.mean(x))
print(np.std(x))

9.5
5.766281297335398


## 집계 함수
* 전체 합 sum
    * axix = None 전체 원소의 합
    * axix = 0 행 방향 즉 각 열들의 합
    * axix = 1 열 방향 (->) 즉 각 행들의 합
* 누적 합 cumsum
* 누적 곱 cumprod

In [10]:
x = np.arange(20).reshape(4, 5)
print(x)

print(np.sum(x, axis = None))
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190
[30 34 38 42 46]
[10 35 60 85]


In [11]:
np.cumsum(x)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

In [12]:
np.cumprod(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

## any
* 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False를 반환한다.

## all
* 모든 원소가 특정 조건을 만족한다면 True, 아니면 False를 반환한다.

In [16]:
x = np.random.randn(10)
x

array([ 0.36233447, -0.46658976, -0.88070287,  0.47069279,  0.22390114,
       -0.75032388,  0.66965759,  0.86392872,  1.32079518, -0.84358512])

In [18]:
np.any(x > 0)

True

In [19]:
np.all(x != 0)

True

## where 함수
* 조건에 따라 선별적으로 값을 선택 가능하다.

In [20]:
x = np.random.randn(10)
x

array([-1.0384254 ,  1.79095825, -0.69105501, -2.2494937 ,  0.61654969,
       -0.11971819, -1.26748967, -0.30693002,  0.73807588,  1.80594321])

In [22]:
np.where(x > 0, x, -1)

array([-1.        ,  1.79095825, -1.        , -1.        ,  0.61654969,
       -1.        , -1.        , -1.        ,  0.73807588,  1.80594321])

## axis
* 몇몇 함수에는 axis keyword 파라미터가 존재한다.
* axix = None 즉 값이 없는 경우에는 전체 원소에 대해 적용한다.
* axix = 값인 경우 해당 axis에 따라선 연산을 적용한다. 이때 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게된다.
* axis의 값이 튜플일 경우 해당 튜플에 명시된 모든 axis에 대해서 연산을 적용한다.

In [25]:
x = np.arange(15).reshape(3,5)
print(x)

print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[15 18 21 24 27]
[10 35 60]


In [26]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [27]:
print(np.sum(z, axis=0))

[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]


In [28]:
print(np.sum(z, axis=1))

[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]


In [29]:
print(np.sum(z, axis=2))

[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]


In [31]:
print(np.sum(z, axis=-2))

[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]


In [32]:
np.sum(z, axis=(0, 2))

array([117, 144, 171, 198])