In [1]:
import numpy as np

## Boolean indexing
* ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링할 수 있다.

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

odd = x % 2 != 0
print(odd)

[75 76 63 34 94  6 49 73 70 11]
[ True False  True False False False  True  True False  True]


In [3]:
x[x % 2 != 0]

array([75, 63, 49, 73, 11])

In [4]:
x[x > 30]

array([75, 76, 63, 34, 94, 49, 73, 70])

### 다중조건 사용하기
* 파이썬 논리 연산지인 and, or, not 키워드는 사용 불가하다.
* & - AND
* | - OR

In [5]:
x[(x % 2 != 0) & (x < 30)]

array([11])