In [2]:
import numpy as np

## np.linalg.inv
* 역행렬을 구할 때 사용하고 모든 차원의 값이 같아야 한다.

### 역행렬
* 어떤 행렬과 곱해서 항등 행렬이 나오게 하는 행렬을 의미한다.

In [3]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.7828529  0.46037467 0.29414263]
  [0.1200889  0.21562875 0.25600594]
  [0.09801326 0.43776293 0.61375547]]

 [[0.46204336 0.81187219 0.56103162]
  [0.9645753  0.69023481 0.82511084]
  [0.88915333 0.30737038 0.54411481]]

 [[0.92082515 0.16936002 0.91349099]
  [0.3960831  0.42656188 0.60819607]
  [0.76791129 0.44571529 0.21572296]]]


array([[[ 1.00000000e+00, -7.51923312e-15,  2.25443273e-15],
        [ 2.37043284e-17,  1.00000000e+00, -1.72797451e-15],
        [ 4.43962802e-16,  5.65476587e-15,  1.00000000e+00]],

       [[ 1.00000000e+00, -4.06194847e-16, -3.27135740e-16],
        [-2.11721254e-16,  1.00000000e+00,  2.60753819e-16],
        [-2.99523799e-18,  1.50175590e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  9.21276376e-17,  6.45731742e-17],
        [-8.53602134e-17,  1.00000000e+00, -7.80527835e-18],
        [-1.36349476e-16,  2.94420440e-16,  1.00000000e+00]]])

## np.linalg.solve
* Ax = B 형태의 선형대수식 솔루션을 제공한다.

* 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
    > x + y = 25
    
    > 2x + 4y = 64
    
$$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$

### 행렬의 곱
* @
* np.matmul

### 행렬의 비교
* np.allclose

In [4]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True