In [1]:
import numpy as np

## 인덱싱
* 파이썬 리스트와 동일하게 인덱스를 이용해 원소에 접근이 가능하다.
* ,를 사용해 각 차원에 인덱스에 접근이 가능하다.

In [5]:
x = np.arange(10)
print(x)

print(x[3])

[0 1 2 3 4 5 6 7 8 9]
3


In [6]:
x = np.arange(20).reshape(4, 5)
print(x)

print(x[1,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
8


In [7]:
x = np.arange(36).reshape(3, 3, 4)
print(x)

x[2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

## 슬라이싱
* ,를 사용하여 각 차원별 슬라이싱이 가능하다.

In [8]:
x = np.arange(10)
print(x)

x[5:]

[0 1 2 3 4 5 6 7 8 9]


array([5, 6, 7, 8, 9])

In [9]:
x = np.arange(20).reshape(4, 5)
print(x)

print(x[1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
x = np.arange(36).reshape(3, 3, 4)
print(x)

x[:1,:,:3]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


array([[[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]]])