In [1]:
import numpy as np

## [브로드캐스팅](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
* Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다.
* 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행한다.

### Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

x * y

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.02100414 0.37945076 0.67174876 0.51374713 0.9026845 ]
 [0.98115278 0.38891591 0.0640032  0.70498947 0.45379358]
 [0.85883899 0.12303315 0.07135675 0.69758494 0.34784249]]


array([[0.        , 0.37945076, 1.34349752, 1.54124139, 3.61073798],
       [4.90576392, 2.33349547, 0.44802243, 5.6399158 , 4.08414218],
       [8.58838995, 1.35336468, 0.85628096, 9.06860421, 4.86979486]])

### Scalar(상수)와의 연산

In [3]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

### Shape이 다른 경우 연산

In [8]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a)
print(b)
print(c)
print(d)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]
[[100 101 102]]


In [5]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [9]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [10]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])